plugins:
  activity_pub_enabled:
    default: true
    client: true
  activity_pub_rate_limit_post_to_inbox_per_minute:
    default: 10
  activity_pub_rate_limit_get_objects_per_minute:
    default: 20
  activity_pub_note_excerpt_maxlength:
    default: 500
  activity_pub_note_link_to_forum:
    default: true
  activity_pub_require_signed_requests:
    default: true
  activity_pub_allowed_request_origins:
    default: ""
    type: host_list
    list_type: simple
  activity_pub_blocked_request_origins:
    default: ""
    type: host_list
    list_type: simple
  activity_pub_delivery_delay_minutes:
    default: 5
    client: true