discourse_activity_pub:
  activity_pub_enabled:
    default: true
    client: true
  activity_pub_rate_limit_post_to_inbox_per_minute:
    default: 10
  activity_pub_rate_limit_get_objects_per_minute:
    default: 20
  activity_pub_note_excerpt_maxlength:
    default: 0
  activity_pub_note_link_to_forum:
    default: true
  activity_pub_require_signed_requests:
    default: true
  activity_pub_allowed_request_origins:
    default: ""
    type: host_list
    list_type: simple
    validator: "ActivityPubSignedRequestsValidator"
  activity_pub_blocked_request_origins:
    default: ""
    type: host_list
    list_type: simple
    validator: "ActivityPubSignedRequestsValidator"
  activity_pub_delivery_delay_minutes:
    default: 5
    min: 1
    client: true
  activity_pub_post_status_visibility_groups:
    default: "0" # everyone
    type: group_list
    allow_any: false
    refresh: true
    client: true
  activity_pub_send_user_agent:
    default: true
  activity_pub_verbose_logging:
    default: false
  activity_pub_object_logging:
    default: false
  activity_pub_logs_max_days_old:
    default: 60
    min: 2
    max: 365